---
- hosts: packstack
  vars:
    repo_host: 192.168.122.1
  remote_user: root
  tasks:
  - name: install the RDO Yum Respository for CentOS / RHEL
    yum: name=https://www.rdoproject.org/repos/rdo-release.rpm state=present
    when: ansible_distribution == "CentOS"

  - name: Enable the correct repositories when on RHEL 7
    command: subscription-manager repos \
             --disable=\* \
             --enable=rhel-7-server-rpms \
             --enable=rhel-7-server-rh-common-rpms \
             --enable=rhel-7-server-optional-rpms \
             --enable=rhel-7-server-extras-rpms \
             --enable=rhel-ha-for-rhel-7-server-rpms \
             --enable=rhel-7-server-openstack-8-rpms \
             --enable=rhel-7-server-openstack-8-director-rpms
    when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")

  - name: Make sure we have yum-utils
    yum: name=yum-utils state=latest

  - name: Make sure we have yum-plugin-priorities
    yum: name=yum-plugin-priorities state=latest


  - include: local_repo.yaml
  - include: local_openstack_repo.yaml

  - name: upgrade all packages
    yum: name=* state=latest

  - name: install the Packstack from Red Hat RHEL-OSP repository or from RDO on Centos
    yum: name=openstack-packstack state=latest

  - name: Execute Packstack
    command: packstack --allinone --cinder-volumes-create=n
