---
- hosts: packstack
  vars:
    repo_host: 192.168.122.1
  remote_user: root
  roles:
    - openstack_repo
    - common
    - local_repo
    - local_repo
    - local_openstack_repo
    - packstack
