#
# Role to define the standard OpenStack repositories
#
# Currently suppots
#  - RDO for Centos 7.x
#  - RH OSP8 for RHEL 7.x
#
---
- name: install the RDO Yum Respository for CentOS / RHEL
  yum: name=https://www.rdoproject.org/repos/rdo-release.rpm state=present
  when: ansible_distribution == "CentOS"

- name: Enable the correct repositories when on RHEL 7
  command: subscription-manager repos \
           --disable=\* \
           --enable=rhel-7-server-rpms \
           --enable=rhel-7-server-rh-common-rpms \
           --enable=rhel-7-server-optional-rpms \
           --enable=rhel-7-server-extras-rpms \
           --enable=rhel-ha-for-rhel-7-server-rpms \
           --enable=rhel-7-server-openstack-8-rpms \
           --enable=rhel-7-server-openstack-8-director-rpms
  when: (ansible_distribution == "RedHat" and
         ansible_distribution_major_version == "7")
